name: finddy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^4.5.1
  carousel_slider: ^4.2.1
  step_progress_indicator: ^1.0.2
  device_preview: ^1.1.0
  dio: ^5.1.2
  camera: ^0.10.3+2
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/img_findy_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PlusJakartaDisplay
      fonts:
        - asset: assets/fonts/PlusJakartaDisplay-Bold.otf
        - asset: assets/fonts/PlusJakartaDisplay-BoldItalic.otf
        - asset: assets/fonts/PlusJakartaDisplay-Italic.otf
        - asset: assets/fonts/PlusJakartaDisplay-Light.otf
        - asset: assets/fonts/PlusJakartaDisplay-LightItalic.otf
        - asset: assets/fonts/PlusJakartaDisplay-Medium.otf
        - asset: assets/fonts/PlusJakartaDisplay-MediumItalic.otf
        - asset: assets/fonts/PlusJakartaDisplay-Regular.otf
    - family: PlusJakartaText
      fonts:
        - asset: assets/fonts/PlusJakartaText-BoldItalic.otf
        - asset: assets/fonts/PlusJakartaText-Italic.otf
        - asset: assets/fonts/PlusJakartaText-Light.otf
        - asset: assets/fonts/PlusJakartaText-LightItalic.otf
        - asset: assets/fonts/PlusJakartaText-Regular.otf
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
        

